<?php echo $this->doctype(); ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('PKP Dashboard Notifications API'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
      ->appendName('viewport', 'width=device-width, initial-scale=1.0')
      ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
  </head>
  <body>
    <?php echo $this->content; ?>
  </body>
</html>
